export default [
  'I Love Being Single',
  'Happy Birthday',
  'Surfs Pumpin ',
  'Just Relax',
  'Running Late',
  "What's Up",
  'You Lost Your Mind',
  'You Need A Back Rub',
  'Let me Tee Off! ',
  'Birthday Tee Off',
  'Still Recovering ',
  'I Like That',
  'Forget That Guy',
];
